[project]
name = "tgbot"
version = "0.1.0"
description = "Improved Telegram bot with polling/webhook, .env config, logging"
requires-python = ">=3.10"
readme = "README.md"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
